create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]


set_property IOSTANDARD LVCMOS33 [get_ports DP]
set_property PACKAGE_PIN J17 [get_ports {An[0]}]
set_property PACKAGE_PIN J18 [get_ports {An[1]}]
set_property PACKAGE_PIN T9 [get_ports {An[2]}]
set_property PACKAGE_PIN J14 [get_ports {An[3]}]
set_property PACKAGE_PIN P14 [get_ports {An[4]}]
set_property PACKAGE_PIN T14 [get_ports {An[5]}]
set_property PACKAGE_PIN K2 [get_ports {An[6]}]
set_property PACKAGE_PIN U13 [get_ports {An[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {An[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {An[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {An[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {An[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {An[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {An[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {An[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {An[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports reset_l]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports cg_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports ce_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports cd_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports cc_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports cb_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports ca_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports cf_OUT]
set_property PACKAGE_PIN C12 [get_ports reset_l]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN H15 [get_ports DP]
set_property PACKAGE_PIN T10 [get_ports ca_OUT]
set_property PACKAGE_PIN R10 [get_ports cb_OUT]
set_property PACKAGE_PIN K16 [get_ports cc_OUT]
set_property PACKAGE_PIN K13 [get_ports cd_OUT]
set_property PACKAGE_PIN P15 [get_ports ce_OUT]
set_property PACKAGE_PIN T11 [get_ports cf_OUT]
set_property PACKAGE_PIN L18 [get_ports cg_OUT]
